= Pemrograman Python: Dari Dasar Sampai Paradigma Pemrograman
Dr. Bambang Purnomosidi D. P. <bambangpdp@gmail.com>
v0.0.1-rev-{localdatetime}
:doctype: book
:toc:
:toc-title: Daftar Isi
:table-caption: Tabel
:source-highlighter: rouge
// style:
// https://github.com/rouge-ruby/rouge/tree/HEAD/lib/rouge/themes
:rouge-style: igor_pro
:sectnums:
:description: File utama buku: Buku Pegangan Pemrograman Python.
:sourcedir: kode-sumber
:includedir: isi
:imagesdir: gambar/isi-buku
// dir tempat hasil asciidoctor-diagram ditempatkan
:imagesoutdir: gambar/cache
:chapter-signifier: Bab
:figure-caption: Gambar
:icons: font
// default: Appendix, diganti dengan "Lampiran"
:appendix-caption: Lampiran

:listing-caption: Kode Sumber 

:xrefstyle: short 

:sectnums!:
== Daftar Gambar
list-of::image[]
<<<

== Daftar Tabel
list-of::table[]
<<<

== Daftar Kode Sumber
list-of::listing[]
<<<
:sectnums:

[preface]
= Kata Pengantar

Buku ini merupakan buku pegangan pemrogaman menggunakan bahasa pemrograman Python. Buku ini dibuat bukan untuk kelengkapan, tetapi terutama ditujukan untuk memberikan pemahaman yang kuat terhadap hal-hal mendasar dan diharapkan bisa menjadi fondasi yang kuat bagi pekerjaan yang terkait dengan pemrograman menggunakan Python. Buku ini sebaiknya digunakan bersama dengan buku-buku serta manual lainnya yang ada pada bagian dokumentasi Python setelah merasa mendapatkan dasar yang kuat.

Atas terbitnya buku ini, penulis mengucapkan terima kasih kepada Penerbit Neo Akselerasi Indonesia serta rekan-rekan penulis di NEO-X yang telah banyak membantu penulis dalam menyelesaikan buku ini.

Tentu saja ada kemungkinan kesalahan dalam buku ini. Jika terdapat kesalah, sila kontak penulis atau bisa juga langsung mengirimkan PR (_Pull Request_) ke repo ini. Akhir kata, selamat mempelajari bahasa pemrograman Python!

Yogyakarta, 2026 +
Dr. Bambang Purnomosidi D. P.

= Bagian I: Latar Belakang dan Operasional Python

[partintro]
--
Bagian ini menjelaskan tentang hal-hal yang bersifat teoritis dan diperlukan untuk memahami ekosistem Python serta cara memulai menggunakan Python. Tujuan utama dari bagian ini adalah pemahaman yang cukup kuat terhadap ekosistem Python serta bisa mulai menggunakan Python di dalam peranti komputasi.
--

include::{includedir}/01-01-pengantar.adoc[]

include::{includedir}/01-02-instalasi.adoc[]

include::{includedir}/01-03-ide.adoc[]

= Bagian II: Sintaksis Dasar Python

[partintro]
--
Bagian ini menjelaskan tentang sintaksis dasar dari bahasa pemrograman Python. Dengan mempelajari dan menguasi sintaksis dasar ini, pembelajar bisa membuat dan mengimplementasikan algoritma dengan menggunakan Python. Meskipun demikian, karena sifatnya masih sintaksis dasar, maka algoritma yang bisa dikerjakan juga merupakan algoritma dasar.
--

include::{includedir}/02-01-dasar.adoc[]

include::{includedir}/02-02-pengendalian-alur.adoc[]

include::{includedir}/02-03-fungsi.adoc[]

include::{includedir}/02-04-struktur-data.adoc[]

include::{includedir}/02-05-modul.adoc[]

include::{includedir}/02-06-operasi-io.adoc[]

include::{includedir}/02-07-error-exception.adoc[]

= Bagian III: Paradigma Pemrograman di Python

[partintro]
--
Bagian ini menjelaskan tentang berbagai paradigma pemrograman yang bisa digunakan di Python. Paradigma pemrograman merupakan cara pandang untuk menyelesaikan masalah pemrograman tertentu. Bagian ini dirasa paling membingungkan oleh para pembelajar Python sehingga sepantasnya bagian ini memerlukan bagian tersendiri. Bagian ini bertujuan supaya para pembelajar bisa menggunakan berbagai modul pihak ketiga yang banyak memanfaatkan berbagai paradigma pemrograman serta mampu menyelesaikan masalah pemrograman menggunakan paradigma tertentu.
--

include::{includedir}/03-01-oop.adoc[]

include::{includedir}/03-02-functional.adoc[]

include::{includedir}/03-03-concurrent-programming.adoc[]

[bibliography]
include::{includedir}/tambahan-00-bibliografi.adoc[]

[appendix]
include::{includedir}/tambahan-01-lampiran.adoc[]

[appendix]
include::{includedir}/tambahan-02-lampiran.adoc[]

[glossary]
= Glosarium

[glossary]
include::{includedir}/tambahan-03-glosarium.adoc[]

[index]
== Indeks
